name: string_validator
version: 0.1.0
author: Suragch (forked from Karan Goel https://github.com/karan/validator.dart)
description: String validation and sanitization for Dart
homepage: https://github.com/suragch/string_validator
documentation: https://github.com/suragch/string_validator
dev_dependencies:
  test: ^1.5.3